import { useState, useEffect } from 'react';
import Head from 'next/head';
import Link from 'next/link';
import Image from 'next/image';

import { sanityClient } from '../lib/sanity';

export default function Navigation() {
  const [navItems, setNavItems] = useState([]);

  useEffect(() => {
    sanityClient
      .fetch(
        `*[_type == "siteConfig"][0]{
          title,
        nav[]->{ 
          _id,
          slug,
          title
        }
      }`
      )
      .then((data) => setNavItems(data))
      .catch(console.error);
  }, []);

  // console.log(navItems.nav);
  const links = navItems.nav;

  return (
    <>
      <Head>
        <title>{navItems.title}</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <nav className='header'>
        <ul>
          {links &&
            links.map((link) => (
              <li key={link._id}>
                <Link href={link.slug.current}>
                  <a>{link.title}</a>
                </Link>
              </li>
            ))}
          <li>
            <a href='#footer'>Kontakta oss</a>
          </li>
        </ul>
      </nav>
    </>
  );
}
